const firmy = [
    {
        nazev: "ORLEN Unipetrol RPA, s.r.o.", 
        adresa: "Záluží 1, 436 70 Litvínov", 
        okres: "Most",
        kontakt: "Dispečink (HZS podniku): 476 161 111", 
        zamestnanci: "4800", 
        doba: "24/7", 
        charakter: "Kritická infrastruktura státu. Extrémně rozsáhlý petrochemický areál (cca 9 km²) s desítkami výrobních jednotek, vysokými kolonami a hustou sítí potrubních mostů. Vlastní vlečka a vnitřní silniční síť.",
        trasa: "Příjezd k hlavní bráně (u čerpací stanice Benzina). Nahlásit se na dispečink HZSP, vjezd povolen po dohodě.",
        rizika: "Extrémní riziko výbuchu a požáru <br> Nebezpečné chemické látky (etylén, čpavek) <br> Rozsáhlý potrubní systém",
        mapa: ["orlen.jpeg", "orlen_detail.png", "orlen_hzsp.jpg"]
    },
    {
        nazev: "Severočeské doly a.s. - Doly Bílina", 
        adresa: "5. května 213, 418 01 Bílina", 
        okres: "Teplice",
        kontakt: "Hlavní dispečink: 417 804 111", 
        zamestnanci: "2500", 
        doba: "24/7", 
        charakter: "Povrchový hnědouhelný lom s obrovskou rozlohou. Terén se neustále mění. Zahrnuje technologické celky pro těžbu, pásovou dopravu a úpravnu uhlí. Vjezd do hloubky lomu pouze s doprovodem.",
        trasa: "Vjezd přes hlavní vrátnici Bílina. Cesta k lomu značena, sledovat pokyny dispečinku.",
        rizika: "Těžká technika, prašnost <br> Riziko závalu / nestabilita terénu <br> Vysoké napětí",
        mapa: "doly_bilina.jpg"
    },
    {
        nazev: "Lovochemie, a.s.", 
        adresa: "Terezínská 57, 410 02 Lovosice", 
        okres: "Litoměřice",
        kontakt: "Hasičský záchranný sbor podniku: 416 561 111", 
        zamestnanci: "900", 
        doba: "24/7", 
        charakter: "Průmyslový chemický areál zaměřený na výrobu hnojiv. Dominantou jsou skladovací sila, výrobní haly kyselin a logistické terminály. Areál je protkán vlečkou.",
        trasa: "Příjezd od kruhového objezdu u dálnice. Vjezd nákladní branou (Gate 2).",
        rizika: "Výroba hnojiv, kyselina dusičná <br> Riziko úniku toxických plynů <br> Sklady nebezpečných látek",
        mapa: "lovochemie.jpeg"
    },
    {
        nazev: "Constellium Decin s.r.o.", 
        adresa: "U Ústecké trati 771/9, 405 02 Děčín", 
        okres: "Děčín",
        kontakt: "Vrátnice / Ostraha: 412 508 111", 
        zamestnanci: "800", 
        doba: "24/7", 
        charakter: "Hutní závod na zpracování hliníku. Komplex tvoří starší i moderní slévárenské a lisovací haly v blízkosti železniční trati. Interiér hal je hlučný s vysokou teplotou.",
        trasa: "Vjezd z ulice U Ústecké trati. Parkování sanitky přímo před administrativní budovou.",
        rizika: "Slévárna hliníku, vysoké teploty <br> Těžká břemena, chemické lázně",
        mapa: "cons.jpeg"
    },
    {
        nazev: "Spolchemie - Spolek pro chemickou a hutní výrobu", 
        adresa: "Revoluční 1930/86, 400 01 Ústí nad Labem", 
        okres: "Ústí n. L.",
        kontakt: "Ohlašovna požárů: 475 271 111", 
        zamestnanci: "850", 
        doba: "24/7", 
        charakter: "Tradiční chemický závod situovaný téměř v centru města. Hustá zástavba starších i nových technologických celků. Velmi členitý terén s úzkými průjezdy mezi budovami.",
        trasa: "Vjezd z ulice Revoluční hlavní branou. V areálu úzké průjezdy!",
        rizika: "Chlor, louhy, pryskyřice <br> Centrum města (hustá zástavba v okolí) <br> Stará infrastruktura",
        mapa: "spolchemie_ul.jpg"
    },
    {
        nazev: "Knauf Insulation spol. s r.o.", 
        adresa: "Průmyslová 95, 417 42 Krupka", 
        okres: "Teplice",
        kontakt: "Vrátnice: 417 569 111", 
        zamestnanci: "250", 
        doba: "24/7", 
        charakter: "Moderní výrobní závod na minerální izolace. Jedna velká centrální hala s kontinuálním provozem pecí. Rozsáhlé venkovní skladové plochy s vysokými stohy balené izolace.",
        trasa: "Příjezd z průmyslové zóny Krupka. Vjezd hlavní branou u expedice.",
        rizika: "Vysokoteplotní pece, skelná vlákna <br> Skladování izolací (vysoké stohy)",
        mapa: "knauf_krupka.jpg"
    },
    {
        nazev: "Nexen Tire Europe s.r.o.", 
        adresa: "Průmyslová 1000, PZ Triangle - Bitozeves", 
        okres: "Louny",
        kontakt: "Hlavní velín (HZS podniku): 414 110 111", 
        zamestnanci: "2300", 
        doba: "24/7", 
        charakter: "Obří moderní automatizovaný závod na výrobu pneumatik. Komplex několika propojených hal s vysokou mírou robotizace a rozsáhlými výškovými sklady.",
        trasa: "Sjezd z dálnice D7 Triangle-Východ. Vjezd přes Gate 1, následovat naváděcí vozidlo HZSP.",
        rizika: "Sklady hořlavin, chemikálie pro výrobu pneu <br> Automatizované zakladačové sklady (vysoké) <br> Riziko požáru gumy",
        mapa: "nexen.jpg"
    },
    {
        nazev: "Yanfeng Automotive Interiors", 
        adresa: "PZ Triangle, 439 48 Bitozeves", 
        okres: "Louny",
        kontakt: "Vrátnice / Bezpečnost: 415 620 111", 
        zamestnanci: "1500", 
        doba: "24/7", 
        charakter: "Montážní a výrobní závod autopříslušenství. Skládá se ze dvou hlavních výrobních hal (A a B) spojených logistickým uzlem. Interiér je čistý, klimatizovaný.",
        trasa: "Vjezd hlavní branou z jižní strany areálu. Sanitky parkují přímo u haly B.",
        rizika: "Plasty, lepidla, čalounické materiály <br> Rozsáhlé výrobní haly",
        mapa: "yanfeng_triangle.jpg"
    },
    {
        nazev: "Eaton Elektrotechnika s.r.o.", 
        adresa: "Komárovská 2406, 430 01 Chomutov", 
        okres: "Chomutov",
        kontakt: "Recepc: 474 610 111", 
        zamestnanci: "600", 
        doba: "06:00 - 22:00", 
        charakter: "Výrobní a montážní závod elektrotechnických komponent. Středně velká moderní hala rozdělená na administrativní část, výrobu a sklady s regálovými systémy.",
        trasa: "Příjezd z ulice Komárovská. Vjezd k zadní nakládací rampě pro sanitu.",
        rizika: "Elektro-komponenty, pájení <br> Rozsáhlé skladové haly",
        mapa: "eaton.jpeg"
    },
    {
        nazev: "Mondi Štětí a.s.", 
        adresa: "Litoměřická 272, 411 08 Štětí", 
        okres: "Litoměřice",
        kontakt: "Dispečink HZSP: 416 801 111", 
        zamestnanci: "1100", 
        doba: "24/7", 
        charakter: "Největší papírenský kombinát v ČR. Rozsáhlý areál u řeky Labe s vysokými regeneračními kotli, papírenskými stroji a obrovskými sklady dřeva a papíru.",
        trasa: "Vjezd přes vrátnici 'Sever'. Sanitky mají přednostní vjezd přes pruh pro hasiče.",
        rizika: "Papírenské stroje, louhy, pára <br> Riziko požáru (sklady papíru a dřeva)",
        mapa: "mondi.jpg"
    },
    {
        nazev: "Kokotí Závody - o.z. Most", 
        adresa: "J.E.Purkyně 272, 430 00 Most", 
        okres: "Most",
        kontakt: "ARO - RES, tel. 2222", 
        zamestnanci: "35", 
        doba: "24/7", 
        charakter: "Fiktivní/testovací objekt v areálu nemocnice. Jedna místnost s vysokou koncentrací sarkasmu a Vladimíra.",
        trasa: "Vběhnout dovnitř a ignorovat Vladimíra.",
        rizika: "Nasranej Vladimír",
        mapa: ""
    },
    {
        nazev: "Žatecká regionální nemocnice, a.s.", 
        adresa: "Husova 2796, 438 01 Žatec", 
        okres: "Louny",
        kontakt: "Vrátnice - 414 110 <b> 111 </b> <br> MOJIP - 414 110 <b> 206 </b>", 
        zamestnanci: "120", 
        doba: "24/7", 
        charakter: "Pětipatrový lůžkový monoblok s přilehlými pavilony (laboratoře, sklady). Součástí je modernizovaný urgentní příjem a lůžková oddělení následné péče.",
        trasa: "Primárně z ul. Husova <br> Alternativní vjezd z ulice Studentská (pod výjezdovou základnou ZZS)",
        rizika: "<b> BSL1 </b> <br> Sklad a rozvod medicinálních plynů <br> Mikrobiologické laboratoře <br> Radiodiagnostické pracoviště",
        mapa: "nemzatec.png"
    },
    {
        nazev: "RAN, s.r.o.", 
        adresa: "Hlavní 61, 439 81 Kryry", 
        okres: "Louny",
        kontakt: "Jaroslav NOVÁK, tel. 777 888 999 <br> Eleonora PODRŽTAŠKOVÁ, tel. 666 777 888", 
        zamestnanci: "50", 
        doba: "<b> Po-Pá: </b> 6:00-15:00 <br> <b> So: </b> 6:00-12:00 <br> <b> Ne: </b> zavřeno", 
        charakter: "<b> výrobní hala (1.NP) </b> - sklad hořlavých kapalin (max. 1500 l) <br> <b> lakovna (max. 60 l) </b> <br> <b> administrativní budova (2.NP) </b> - kanceláře, sociální zařízení, šatny, jídelna, plynová kotelna <br> <b> venkovní prostor v areálu </b> - oblouková hala, sklady, sklad tlakových lahví",
        trasa: "<b> Od centra směr Očihov </b> na levé straně na konci obce (naproti ČS Commodity Petrol) <br> <b> Od obce Očihov směr centrum </b> na pravé straně na začátku obce (naproti ČS Commodity Petrol)",
        rizika: "Přítomnost zemního plynu, acetylenu, kyslíku, helia, dusíku CO2",
        mapa: "ran.png"
    },
    {
        nazev: "Hitachi Energy Czech Republic s.r.o.", 
        adresa: "Průmyslová 137, 430 01 Chomutov", 
        okres: "Chomutov",
        kontakt: "Vrátnice: 474 617 111", 
        zamestnanci: "450", 
        doba: "06:00 - 18:00", 
        charakter: "Závod na výrobu a testování transformátorů a komponent pro energetiku. Velká montážní hala s jeřábovými drahami a speciálními zkušebnami vysokého napětí.",
        trasa: "Příjezd k hlavní recepci Hitachi. Pro vjezd do haly použít boční bránu 'C'.",
        rizika: "Vysoké napětí, testovací laboratoře <br> Olejové náplně transformátorů",
        mapa: "hitachi.jpeg"
    }
];